name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '!frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./backend
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./backend
      run: cargo test --verbose
    - name: Build release and call executable
      working-directory: ./backend
      run: cargo run --release -- --help
    - name: Build and Push template image
      uses: docker/build-push-action@v1 # https://github.com/docker/build-push-action
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        path: ./backend/
        dockerfile: ./backend/Dockerfile
        repository: tetcoin/tetcore-telemetry-backend
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        tags: latest
        add_git_labels: true
